### ISSUE TITLE
Unable to install in Docker distribution of MineMeld

### ISSUE THREAD

**Issue by dwatson-data3** [mr-torgue/mmcabby#1]
Hi Mr Torgue.
Have you had any success getting this extension to work with docker MineMeld distribution?

The engine/core directory didn't exist here.

I tried downloading the core git repo to engine/core, modifying the requirements.txt as recommended, but get errors when running "/opt/minemeld/engine/current/bin/python setup.py install".

creating build/temp.linux-x86_64-2.7/minemeld/packages/gdns
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DHAVE_NETDB_H= -I/usr/include/python2.7 -c minemeld/packages/gdns/_ares.c -o build/temp.linux-x86_64-2.7/minemeld/packages/gdns/_ares.o
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Any advice would be greatly appreciated. Thanks.

**Comment by mr-torgue** [comment]
Hello, 

I have not tested it with docker before. So far the installation is going well, but I have not been able to get it working yet.
Engine can be accessed in the docker container: docker exec -it minemeld /bin/bash. It is however better to solve the dependency issues, so it will work right out of the box. I will try to fix this.

Regards,
mr_torgue

**Comment by dwatson-data3** [comment]
Thanks mr_torgue,

via the docker container (docker exec -it minemeld /bin/bash) was where I tried cloning the engine/core and re-running the setup. Unfortunately I couldn't get it to work.
I don't often work in linux, but I am happy to assist if I can, time permitting.

Regards,
Dave

**Comment by mr-torgue** [comment]
Okay, so I looked into the dependency issues. The main problem is that the minemeld-core package requires specific versions of python packages: libtaxii==1.1.107 and pytz==2015.4 (there are more, but these 2 cause the issues). The latest version of cabby (mmcabby uses this library) uses libtaxii>=1.1.111 and pytz>=2017.2. 

I tried to find an older version of cabby for which 1.1.107 and 2015.4 will work. Unfortunately there is no such version. cabby 0.1.8 comes closest. But that is an internal release and is not on pypi and contains some mistakes. So what I have done is clone the cabby repository and change the requirements so there are no conflicts. It is a bit of a dirty fix, but it seems to work. It should now work without issues, maybe a clean reinstall is needed. It is version v1.0.1.

I think the main problem is with the minemeld developers. By requiring specific versions of python packages you will get dependency issues very fast. It makes it harder to find compatible packages.

I updated the readme on my github repository. So I think it should be clear. If not, please ask.

**Comment by dwatson-data3** [comment]
Hi mr-torgue, I was able to install and use the extension today without any issues.
Thanks for your amazing work.
Regards,
Dave

**Comment by mr-torgue** [comment]
Great! Thanks for the comment, it triggered me to finally do something about the dependency problem :)
